// <auto-generated />
namespace Gp_V1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editUsersTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editUsersTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202105201242435_editUsersTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
